### ISSUE TITLE
Liste in secrets (statt Plex/Trakt)

### ISSUE THREAD

**Issue by rix1337** [crack00r/Flexget-Config#1]
Hi,

bisher läuft bei mir Alles über pyload (und dortige plugins haben eine einfache .txt datei als Watchlist).

Ich würde mich über eine Möglichkeit freuen, statt trakt/plex eine solche liste zu verwenden.

Also einfach irgendwo in der secrets-Datei:

```
-Serien
   -Serie XY
   -Serie ZW
   - ...
-Filme
   -Blablubb
   -Anderer Film
   - ...
```

Wäre das umzusetzten?

**Comment by crack00r** [comment]
Das kannst du bereits, einfach mal damit rum spielen.
http://flexget.com/wiki/Cookbook/Series/Preset
