### ISSUE TITLE
Question regarding correct setup

### ISSUE THREAD

**Issue by lorgas** [crack00r/Flexget-Config#11]
Hallo,

Ich habe einen Plex Server und habe dort das trakt plugin installiert. Also muss ich nur noch meine trakt daten in dein script eintragen und es sucht automatisch nach episoden die in meiner aktuellen sammlung fehlen und nach neuen episoden/filmen, korrekt ? 
Oder muss ich das anders konfigurieren? Bei trakt bzw. hier bei diesem skript?
Perfekt wäre es wenn die scene files .to  wieder gehen würde und man serien junkies komplett rausnehmen könnte.

gruß

**Comment by snickers2k** [comment]
ja, so sollte es laufen.

scene...pw/to ist offline
