### ISSUE TITLE
How to ? 

### ISSUE THREAD

**Issue by SlashGIP** [crack00r/Flexget-Config#13]
Hi, ich habe versucht alles nach Anleitung durchzuführen, erhalte aber nie ein Ergebnis in irgendeiner Form. 

Egal wie ich meine Watchlist auf Trakt fülle, kommt kein Accepted zu stande.

Selbst wenn etwas gefunden wird, "Accepted", wird es in der nächsten Zeile direkt "Rejected" aufgrund von "by urlrewriting plugin because no Episode found" 

Ich steh mit meinem Latein am Ende. Pls help

**Comment by SlashGIP** [comment]
Hi, 

also ich vermute, dass das Problem  damit zu tun hat, dass Serienjunkies die einzelnen Serien in Staffeln verpackt und nicht mehr als Einzelserie als download zur Verfügung stellt. Der Crawler findet zwar die einzelnen Folgen und Acceptet diese, jedoch Rejected diese gleich wieder weil anscheinend keine Episoden im Link gefunden werden. Wäre jetzt meine Vermutung.

[Log](https://pastebin.com/h4s7gTmj)

**Comment by snickers2k** [comment]
Ja, richtig vermutet. https://discuss.flexget.com/t/help-with-urlrewriting-no-episode-found/3960/8

**Comment by SlashGIP** [comment]
Hi, wollte nur kurz fragen, ob du es getestet hast und noch eine Frage hinterher schieben:
kann man im config.yml irgendwie eine Anmeldung in einem Forum vollziehen? Beispiel um den RSS Feed von boerse.to zu erhalten? Den kriege ich nur, wenn ich im Forum angemeldet bin. Gibt es da irgendeinen Login Codeschnipsel für die config.yml. Danke für die Unterstützung.

**Comment by snickers2k** [comment]
So funktioniert flexget mit rss nicht. der download-link muss vom rss direkt übertragen werden - und nicht zu einem thread, wo der link drin steht. dafür gibt es die plugins aus dieser config. müssen aber immer umständlich angepasst werden.

**Comment by SlashGIP** [comment]
Hi, danke für die schnelle Antwort. Sorry, dann habe ich mich falsch ausgedrückt. https://boerse.to/forum/serien.32/index.rss das wäre der Link dazu. im RSS Feed selber wird der download link angezeigt. Man muss sich anscheinend aber erst einloggen irgendwie und das wäredie Frage ob es dafür eine Möglichkeit gibt.

**Comment by snickers2k** [comment]
ich bin auf boerse angemeldet. aber dein link führt zu einem rss, in dem nur thread-verlinkungen stehen?! jedenfalls im browser. oder geht es nur mit rss-readern, die einen  login-funktion haben?

**Comment by snickers2k** [comment]
an boerse hätte ich selber interesse. aber leider sehe ich keine  möglichkeit.

**Comment by SlashGIP** [comment]
Moin, ich benutze aktuell feedly. Damit gehts aber nicht. :-( Bin in dem rss Thema noch nicht so lange drin. Bin da erst am testen und einlesen usw. Also in den Anfängen. :) 

HAst du SJ bei dir mal getestet ob du einzelne Folgen laden kannst? Du hast in einem anderen Issue Thread hier geschrieben, dass du deine Config anders nutzt als die anderen. 

Ja, mir antwortet dort auch niemand wirklich. Leider. ICh habe ja extra auf den alten Post verwiesen, damit da keiner sauer wird. :)

Grüße

**Comment by snickers2k** [comment]
Flexget an einen speziellen RSS anzupassen ist doch recht tricky. Könnte man mal im Forum besprechen.
