### ISSUE TITLE
Keine Funktion?

### ISSUE THREAD

**Issue by sixteeN11** [crack00r/Flexget-Config#14]
> 2018-09-11 21:17 CRITICAL task          Specials        BUG: Unhandled error in plugin include: [Errno 2] No such file or directory: '/root/.flexget/Specials.yml'
> 2018-09-11 21:17 CRITICAL manager       Specials        An unexpected crash has occurred. Writing crash report to /root/.flexget/crash_report.2018.09.11.211741846768.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.14.20
> 2018-09-11 21:17 WARNING  task          Specials        Aborting task (plugin: include)
> 2018-09-11 21:17 CRITICAL task          Specials2       BUG: Unhandled error in plugin include: [Errno 2] No such file or directory: '/root/.flexget/Specials2.yml'
> 2018-09-11 21:17 CRITICAL manager       Specials2       An unexpected crash has occurred. Writing crash report to /root/.flexget/crash_report.2018.09.11.211741994868.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.14.20
> 2018-09-11 21:17 WARNING  task          Specials2       Aborting task (plugin: include)
> 2018-09-11 21:17 CRITICAL template      YouTube-Personal-Playlist Unable to find template pyload-YouTube for task YouTube-Personal-Playlist
> 2018-09-11 21:17 WARNING  task          YouTube-Personal-Playlist Aborting task (plugin: template)
> 2018-09-11 21:17 CRITICAL task          eBooks          BUG: Unhandled error in plugin include: [Errno 2] No such file or directory: '/root/.flexget/eBooks.yml'
> 2018-09-11 21:17 CRITICAL manager       eBooks          An unexpected crash has occurred. Writing crash report to /root/.flexget/crash_report.2018.09.11.211742284881.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.14.20
> 2018-09-11 21:17 WARNING  task          eBooks          Aborting task (plugin: include)

Hallo,
leider bekomme ich massiv viele Fehler wenn ich einfach das ganze Paket nehme und auf meinen Pi schmeiße, ich hatte es mal laufen, ist aber auch schon ein paar Tage her.

Er meckert youtube an, er meckert ebooks an (Was ich nicht brauche) und die trakt liste importiert er nicht so richtig @snickers2k hast du eine Lösung dafür? Soll ich mal einen gesamten Log liefern?

**Comment by sixteeN11** [comment]
https://pastebin.com/AstC5XDa

Das ist der crash report

**Comment by snickers2k** [comment]
bevor ich mir das weiter anschaue.. hast du in den options ganz unten alles auf disable?

**Comment by snickers2k** [comment]
okay.. update kommt die Tage. Muss mal sehen wie ich das umgehe.

**Comment by sixteeN11** [comment]
Habe das gefixt indem ich Specials, YouTube und EBooks auskommentiert habe. Aber er schluckt meine Trakt Liste nicht bzw. Liest sie nicht ein. 

Ist dir dazu was bekannt?

**Comment by snickers2k** [comment]
Ja, das ist quasi ein quick-fix.. aber ich selbst nutze die tasks ja, also will ich das lieber vernünftig umgehen.

Bei mir läuft alles... Evtl die quali falsch gewählt? Was ist der reject Grund?

**Comment by sixteeN11** [comment]
Mittlerweile habe ich wohl die Trakt API nicht mehr auf meiner Seite, bekomme nur noch ein 403. Haben die ein Limit pro Tag bzw pro Stunde? 

Watchlist scheint nicht korrekt eingelesen zu werden, funktioniert das Search Plugin überhaupt noch? Sodass Filme und Serien die auf der Liste sind, geladen werden.

Poste später noch den kompletten log wenn Trakt wieder funktioniert 😅

**Comment by sixteeN11** [comment]
Im Forum hatte ich gelesen, dass du auch überlegst eine kostenpflichtige Version anzubieten weil sich der Aufwand nicht mehr lohnt es kostenfrei zu machen.

Ist das noch akut? Wäre interessant.

**Comment by snickers2k** [comment]
Trakt hat auch ein API limit.. aber ziemlich hoch.. 
Search_Plugin funktioniert.. so wie alles, eig.. abgesehen von meinen eigenen tasks, die ich nicht supporte und daher umgangen werden müssen (hast du ja mit auskommentieren gelöst).

Schick nochmal den ganzen Log, nachdem es nun durchläuft (oder mehr als vorher).

Kostenpflichtige Version wird es nicht geben.. Dann würde ich mich zu sehr verpflichtet fühlen -  und oft habe ich einfach keine Zeit.

**Comment by sixteeN11** [comment]
https://pastebin.com/WWfqqVS8

Ich habe den Serien Teil mal raus genommen, weil ich eh gerade keine Serien gucke,
mich interessiert nur die Movies Section und wenn die läuft dann später ggf auch Serien.

**Comment by sixteeN11** [comment]
**2018-09-18 10:50 VERBOSE  trakt_list    Movies_Watchlist_Stream_DE_Main Retrieving `movies` list `{? trakt.favorites ?}`
2018-09-18 10:50 CRITICAL plugin        Movies_Watchlist_Stream_DE_Main Could not retrieve list from trakt (405 Client Error: Method Not Allowed for url: https://api.trakt.tv/users/me/lists/-trakt.favorites-/items)
2018-09-18 10:50 WARNING  task          Movies_Watchlist_Stream_DE_Main Aborting task (plugin: list_match)**

Ist der aktuelle Fehler der die Tasks abbricht.

**Comment by snickers2k** [comment]
"Favorites" liste auf trakt erstellen. Die muss so heißen, wie in den Options.
Werde da nochmal schauen, ob ich den error umgehen kann, wenn man keine Favoriten-Liste hat.

**Comment by sixteeN11** [comment]
Wo muss ich denn in den Options diese Liste festlegen?
Habe auf trakt eine Liste "Favorites" erstellt, Fehler ist aber nach wie vor da.

**Comment by snickers2k** [comment]
ist schon in den options.. 

`Favorites: Favorites ## Optional ## Name of your trakt-favorites list. Works without as well, just a visual thing inside trakt`

Wenn auf trakt.tv eine Liste "Favorites" ist, sollte alles funktionieren. tut es bei mir... und allen anderen :D

**Comment by sixteeN11** [comment]
In welcher Zeile der options.yml ?
Irgendwie klappt das so gar nicht bei mir, habe aber eigentlich alles so gemacht wie du.

Wo ist denn der Fehler?

**Comment by snickers2k** [comment]
Oha.. die Options hier auf git ist älter, als die, die ich nutze :D huch... Naja, dann weiß ich ja woran es liegt. Fix kommt die Tage.

**Comment by sixteeN11** [comment]
Kannst du die Options nur eben hochladen oder mir sagen wo es hängt? :D

**Comment by snickers2k** [comment]
nur eben hochladen.. da sind meine paswörter drin ;)  muss das schon eben angleichen.

unter "trakt" eine zeile 
`Favorites: Favorites `
einfügen. Aber dann kommt  sicher der nächste Fehler.

**Comment by sixteeN11** [comment]
Ja das wäre klasse, wenn du das tun könntest 😄
Habe die Zeile eingefügt, leider bemängelt er den Fehler immer noch

**Comment by snickers2k** [comment]
probier nochmal aus. Zur Not müssen die fehlenden .yml files noch erstellt werden. Aber schick mir dann mal den log

**Comment by sixteeN11** [comment]
Sauber Danke!
Geht bei dir das Searchplugin noch? Er schreibt immer er konnte nichts finden .. aber auf der Webseite mit dem Shortcut ist alles zu finden

**Comment by snickers2k** [comment]
Ein bisschen mehr Infos bitte. Geht jetzt alles? Also ohne auskommentieren? Er meckert nicht über mehr über  fehlende .yml files ?
Ja, Search geht. Logfile....

**Comment by topy** [comment]
Hab flexget mit der config auch ans laufen bekommen und sehe keine Fehler
mehr. Allerdings findet der bei mir auch nichts. Ich denke ich schaffe es
die Tage mir das mal genauer anzuschauen

snickers2k <notifications@github.com> schrieb am Mi., 26. Sep. 2018, 00:45:

**Comment by sixteeN11** [comment]
Genau das einzige was noch hängt ist der search, habe mir den Parser schon angesehen das sind ein paar Änderungen nötig, vielleicht schaff ich das ja auch @topy

**Comment by snickers2k** [comment]
Nun ist aber auch mal gut sixteen. Entweder du lieferst die Infos, oder du lässt es ganz. Aber hör auf hier die Pferde verrückt zu machen.
.... logfiles ....
Bei mir funktioniert alles.

`2018-09-26 16:04 VERBOSE  discover      Movies_10Star_HighQuality_Search Searching for `Avatar (2009)` with plugin `searchHdarea` (13 of 24)
2018-09-26 16:04 VERBOSE  BaseSearchPlugin Movies_10Star_HighQuality_Search Entry -> Title:Avatar.2009.Extended.Cut.2160p.4K.2K-DCPRip.German.Dubbed.DTS.DL.x265-NCPX, Link: https://filecrypt.cc/Container/26442BCEDB.html, Size: 66661.8347168
2018-09-26 16:04 VERBOSE  BaseSearchPlugin Movies_10Star_HighQuality_Search Entry -> Title:Avatar.2009.Extended.Cut.2160p.4K.2K-DCPRip.German.Dubbed.DTS.DL.x265-NCPX, Link: https://filecrypt.cc/Container/F92B0CF618.html, Size: 66661.8347168`

**Comment by sixteeN11** [comment]
Sorry falls ich dir auf den Schlips getreten bin, ich liefere dir heute Abend die Logs. War nur eine Zwischenfrage :)

**Comment by snickers2k** [comment]
Alles gut. Sorry, war etwas genervt. Bin noch auf Arbeit und bekomme zuviele Emails ;D

**Comment by snickers2k** [comment]
Mysteriös .. der 10-star-task lief ja bekanntlich bei mir erfolgreich durch.
Die generelle Movie-Suche bricht dann aber irgendwann ab.

`2018-09-26 17:32 CRITICAL task          Movies_Watchlist_Search_DE_Main BUG: Unhandled error in plugin discover: (sqlite3.OperationalError) database is locked [SQL: u'SELECT bluray_genres.name AS bluray_genres_name \nFROM bluray_genres, bluray_movie_genres \nWHERE ? = bluray_movie_genres.movie_id AND bluray_genres.name = bluray_movie_genres.genre_name'] [parameters: (197340,)] (Background on this error at: http://sqlalche.me/e/e3q8)
2018-09-26 17:32 WARNING  task          Movies_Watchlist_Search_DE_Main Aborting task (plugin: discover)
2018-09-26 17:32 CRITICAL task          Movies_Watchlist_Search_DE_Main BUG: Unhandled error in plugin status: (sqlite3.OperationalError) database is locked [SQL: u'SELECT status_task.task AS status_task_task, status_task.id AS status_task_id \nFROM status_task \nWHERE status_task.id = ?'] [parameters: (10,)] (Background on this error at: http://sqlalche.me/e/e3q8)
2018-09-26 17:32 WARNING  task          Movies_Watchlist_Search_DE_Main Aborting task (plugin: status)
2018-09-26 17:32 ERROR    task          Movies_Watchlist_Search_DE_Main abort handlers aborted: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 617, in _execute
    self.__run_task_phase('abort')
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 453, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 519, in __run_plugin
    self.abort(msg, traceback=traceback)
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 370, in abort
    raise TaskAbort(reason, silent=silent)
TaskAbort
`
Hast du den gleichen Error @sixteeN11 ?

**Comment by sixteeN11** [comment]
Nein der läuft bei mir durch, das sieht bei dir aber nach einem Problem mit der Datenbank aus. Kannst du die testweise mal neu erstellen? „database is locked“

**Comment by sixteeN11** [comment]
Hi zusammen,

Zwischenfrage, wer arbeitet noch mit PyLoad? Manche meiner Downloads schlagen fehl mit Fehler: invalid() takes exactly 1 argument (2 given)

Weiß einer woran das liegt?
Muss sie ca 2-3 mal neu starten bis sie durch laufen ... super nervig 🤷🏼‍♂️

Danke...

**Comment by snickers2k** [comment]
das ist wohl eher ein pyload problem. aus ähnlichen gründen nutze ich seit 2 jahren jdownloader.
