### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by chest069** [crack00r/Flexget-Config#16]
Hey, I am new to all of this and I am trying to use this with Windows 10 and JDownloader2.
Do you have instructions for setting this up in Windows 10.
Thanks for any help. If this is not the correct place for help can you link me to where I can get help?

**Comment by snickers2k** [comment]
sorry, no support here for windows. it's not that i wouldn't want to, but i guess nobody uses Windows anymore ?! At least i don't. Try a VM with debian
