### ISSUE TITLE
trakt, imdb watchlist wird nicht geladen.

### ISSUE THREAD

**Issue by usman2006** [crack00r/Flexget-Config#17]
hallo,

hab auf raspiberry 3b+ flexget nach deiner Anleitung laufen.
Aber die config scheint nicht bei mir richtig zu funksonieren.
trakt ist auth. und es findet auch meine gesehene show aber von der watchlist wird nichts geladen bzw. gesucht und die search funktion liefert auch nichts.
bsp wird tbbt mit sj.org plugin gsucht aber der findet nichts

log
https://pastebin.com/SzbgUi3p

options
https://pastebin.com/WjamWf4s

danke

**Comment by snickers2k** [comment]
config ist updated .. sollte wieder funktionieren.
imdb ist geschichte. die api ist mist.
größen funktionieren zZ nicht .. muss ich mir nochmal anschauen.
