### ISSUE TITLE
Python 3 Upgrade?

### ISSUE THREAD

**Issue by WtfJoke** [crack00r/Flexget-Config#18]
Hi snickers,

Danke für deine Arbeit hier. Ich versuche gerade wieder flexget zum laufen zu kriegen (bin aber noch nicht soweit).

Steht es bei dir auf dem Plan die Skripte auf Python 3 upzugraden? 
Habe gemerkt, dass deine Skripte noch auf Python 2 ausgelegt sind

**Comment by snickers2k** [comment]
Hey.
Leider kommen die Plugins nicht von mir - und ich fürchte auch, dass meine python-Skills dafür nicht ausreichen. Würde mich also freuen, wenn dass jemand portieren könnte :)

**Comment by WtfJoke** [comment]
Ja futurize ist ein Schritt in die richtige Richtung ;)

**Comment by snickers2k** [comment]
done - danke topy
