### ISSUE TITLE
Ombi error

### ISSUE THREAD

**Issue by 9Mad-Max5** [crack00r/Flexget-Config#20]
Hast du den folgenden Fehler auch.
Er scheint was mit der config nicht zu passen.
Fehlt da ein leerzeichen oder sowas für flexget?

[/tasks/Sync_Ombi_Series] The key `ombi_list` is not valid                                                                                                                           here. Only known plugin names are valid keys.

**Comment by 9Mad-Max5** [comment]
Mhm sieht so aus als wäre ombi in der aktuellen version noch nicht enthalten von flexget. Welche version verwendet ihr denn?

**Comment by snickers2k** [comment]
du musst aber schon den plugins ordner laden ;)
darüber wird dann auch die ombi funktion eingebunden.
