### ISSUE TITLE
Filmsuche nur auf Englisch

### ISSUE THREAD

**Issue by rix1337** [crack00r/Flexget-Config#4]
Mit der aktuellen Config scheint über PHP. nur nach Englischen Titeln gesucht zu werden

```2016-03-05 11:00 ERROR    search_rss    Movies_Watchlist_Search Error attempting to get rss for http://oldenburgknights.de/manuel/hd-area/hd-area.php?var=The%20Man%20in%20the%20Iron%20Mask%201998: Received invalid RSS content from task Movies_Watchlist_Search (http://oldenburgknights.de/manuel/hd-area/hd-area.php?var=The%20Man%20in%20the%20Iron%20Mask%201998)```

Ließe sich das noch zB über den IMDb Titel anpassen?

**Comment by crack00r** [comment]
Das liegt an Trakt, da die nur englische Titel liefern. 
Wenn du zb imdb watchlist als Quelle nimmt, geht deutsch.

**Comment by rix1337** [comment]
Alles klar
