### ISSUE TITLE
searchSerienjunkies broken

### ISSUE THREAD

**Issue by fluver** [crack00r/Flexget-Config#7]
I noticed the searchSerienjunkies plugin used to discover new episodes returns no entrys. 
Apparently they broke the search function on the website, using a external search engine works to some degree (e.g. google "site:serienjunkies.org big bang theory S01E01 -site:board.serienjunkies.org"). 
Maybe we can get the show name from a external database(tvdb, imdb) and build a valid sj.org link.
Any more ideas?

**Comment by CENGOiSM** [comment]
Uploaded a new version, should fix the empty entries. Probably will cause errors, because I couldn't verify if the code is working fine - still need to install flexget.
Feel free to try it out and report any issues. 👍
